local palette = require 'nana.palette'

return {
  -- built-in options
  Character = { fg = palette.yellow },
  Boolean = { fg = palette.lavender },
  Comment = { fg = palette.grey },
  Constant = { fg = palette.lavender },
  ColorColumn = { bg = palette.base2 },
  Conceal = { fg = palette.base2 },
  CurSearch = { bg = palette.basehighlight },
  CursorColumn = { bg = palette.base2 },
  CursorLine = { bg = palette.base1 },
  CursorLineNr = { fg = palette.base7, bg = palette.base2 },
  Define = { fg = palette.crimson },
  Debug = { bg = palette.yellow },
  DiffAdd = { fg = palette.diff_add },
  DiffChange = { fg = palette.diff_change },
  DiffDelete = { fg = palette.diff_remove },
  DiffText = { fg = palette.diff_text },
  Directory = { fg = palette.blue },
  ErrorMsg = { fg = palette.red, bg = palette.basewarn },
  FloatBorder = { bg = palette.base2 },
  Float = { fg = palette.orange },
  FloatTitle = { fg = palette.base7 },
  Identifier = { fg = palette.white },
  IncSearch = { bg = palette.basehighlight },
  Keyword = { fg = palette.crimson, italic = true },
  Label = { fg = palette.base8 },
  LineNr = { fg = palette.base5, bg = palette.base2 },
  Macro = { fg = palette.crimson },
  MatchParen = { bg = palette.basehighlight },
  NonText = { fg = palette.base4, bg = palette.base2 },
  Normal = { fg = palette.white, bg = palette.base0 },
  NormalFloat = { bg = palette.base3 },
  NormalNC = { fg = palette.base7, bg = palette.base2 },
  Number = { fg = palette.lavender },
  Operator = { fg = palette.crimson },
  Pmenu = { fg = palette.white, bg = palette.base3 },
  PmenuSelBold = { fg = palette.basehighlight, bg = palette.orange },
  PmenuSbar = { bg = palette.base3 },
  PmenuSel = { bg = palette.basehighlight },
  PmenuThumb = { fg = palette.lavender, bg = palette.green },
  PreCondit = { fg = palette.crimson },
  PreProc = { fg = palette.green },
  Question = { fg = palette.white, bg = palette.base3 },
  QuickFixLine = { fg = palette.base7, bg = palette.base4 },
  Scrollbar = { bg = palette.base3, fg = palette.base3 },
  Search = { bg = palette.basehighlight },
  SignColumn = { fg = palette.white, bg = palette.base2 },
  Special = { fg = palette.crimson },
  SpecialChar = { fg = palette.crimson },
  SpecialKey = { fg = palette.crimson },
  Statement = { fg = palette.crimson },
  String = { fg = palette.yellow },
  Title = { fg = palette.green },
  Type = { fg = palette.green },
  Typedef = { fg = palette.lavender },
  Visual = { bg = palette.basehighlight },
  VisualNOS = { bg = palette.base3 },
  Whitespace = { fg = palette.base2 },

  -- Diagnostics
  dbui_tables = { fg = palette.white },
  CursorWord0 = { bg = palette.white, fg = palette.black },
  CursorWord1 = { bg = palette.white, fg = palette.black },
  DiagnosticError = { fg = palette.red },
  DiagnosticWarn = { fg = palette.orange },
  DiagnosticSignError = { fg = palette.red },
  DiagnosticHint = { fg = palette.blue },
  DiagnosticInfo = { fg = palette.basehighlight },
  DiagnosticSignWarn = { fg = palette.orange },
  DiagnosticSignInfo = { fg = palette.basehighlight },
  DiagnosticSignHint = { fg = palette.blue },
  DiagnosticVirtualTextError = { fg = palette.red },
  DiagnosticVirtualTextWarn = { fg = palette.orange },
  DiagnosticVirtualTextInfo = { fg = palette.white },
  DiagnosticVirtualTextHint = { fg = palette.blue },
  DiagnosticUnderlineError = { bg = palette.basewarn },
  DiagnosticUnderlineWarn = { undercurl = true, sp = palette.orange },
  DiagnosticFloatingError = { fg = palette.red },
  DiagnosticFloatingHint = { fg = palette.blue, bg = palette.base3 },
  NvimTreeFolderName = { fg = palette.white },
  NvimTreeRootFolder = { fg = palette.crimson },
  NvimTreeSpecialFile = { fg = palette.white, style = 'NONE' },

  -- Telescope
  TelescopeBorder = { fg = palette.base6 },
  TelescopeMultiSelection = { fg = palette.orange, bg = palette.basehighlight },
  TelescopeMatching = { bg = palette.basehighlight },
  TelescopeNormal = { fg = palette.base7, bg = palette.base0 },
  TelescopePreviewWrite = { fg = palette.blue },
  TelescopeSelection = { fg = palette.white, bg = palette.base3 },
  TelescopeSelectionCaret = { fg = palette.grey },

  -- gitsigns
  diffAdded = { fg = palette.green },
  diffRemoved = { fg = palette.diff_remove },
  GitSignsCurrentLineBlame = { fg = palette.basehighlight },

  -- lualine
  LuaLineDiffAdd = { fg = palette.green },
  LuaLineDiffChange = { fg = palette.orange },
  LuaLineDiffDelete = { fg = palette.red },

  -- todo-comments
  TodoFgTODO = { fg = palette.base6 },

  -- Treesitter
  ['@annotation'] = { fg = palette.lavender },
  ['@attribute'] = { fg = palette.green },
  ['@boolean'] = { fg = palette.lavender },
  ['@character'] = { fg = palette.yellow },
  ['@character.special'] = { fg = palette.lavender },
  ['@comment'] = { fg = palette.base5, italic = true },
  ['@conceal'] = { fg = palette.grey },
  ['@conditional'] = { fg = palette.crimson },
  ['@conditional.ternary'] = { fg = palette.crimson },
  ['@constant'] = { fg = palette.lavender },
  ['@constant.builtin'] = { fg = palette.lavender },
  ['@constant.macro'] = { fg = palette.lavender },
  ['@constructor'] = { fg = palette.green },
  ['@debug'] = { fg = palette.crimson },
  ['@define'] = { fg = palette.blue },
  ['@error'] = { fg = palette.red },
  ['@exception'] = { fg = palette.crimson },
  ['@field'] = { fg = palette.white },
  ['@float'] = { fg = palette.orange },
  ['@function'] = { fg = palette.green },
  ['@function.builtin'] = { fg = palette.blue },
  ['@method'] = { fg = palette.green },
  ['@method.builtin'] = { fg = palette.blue },
  ['@include'] = { fg = palette.crimson },
  ['@keyword'] = { fg = palette.crimson },
  ['@keyword.function'] = { fg = palette.blue },
  ['@keyword.operator'] = { fg = palette.crimson },
  ['@keyword.return'] = { fg = palette.crimson },
  ['@label'] = { fg = palette.crimson },
  ['@markup.heading'] = { fg = palette.base8, bold = true },
  ['@markup.italic'] = { fg = palette.base8, italic = true },
  ['@markup.strong'] = { fg = palette.base8, bold = true },
  ['@markup.raw.markdown_inline'] = { fg = palette.base6, bg = palette.base3 },
  ['@markup.link'] = { fg = palette.blue, underline = true },
  ['@spell.markdown'] = { fg = palette.base7 },
  ['@namespace'] = { fg = palette.lavender },
  ['@number'] = { fg = palette.lavender },
  ['@operator'] = { fg = palette.crimson },
  ['@parameter'] = { fg = palette.orange, italic = true },
  ['@property'] = { fg = palette.white },
  ['@punctuation.bracket'] = { fg = palette.white },
  ['@punctuation.delimiter'] = { fg = palette.white },
  ['@punctuation.special'] = { fg = palette.crimson },
  ['@reference'] = { fg = palette.white },
  ['@repeat'] = { fg = palette.crimson },
  ['@string'] = { fg = palette.yellow },
  ['@string.escape'] = { fg = palette.lavender },
  ['@string.regex'] = { fg = palette.lavender },
  ['@string.special'] = { fg = palette.lavender },
  ['@symbol'] = { fg = palette.lavender },
  ['@tag'] = { fg = palette.crimson },
  ['@tag.attribute'] = { fg = palette.green },
  ['@tag.delimiter'] = { fg = palette.white },
  ['@text'] = { fg = palette.white },
  ['@type'] = { fg = palette.green },
  ['@type.builtin'] = { fg = palette.blue },
  ['@type.qualifier'] = { fg = palette.crimson },
  ['@variable'] = { fg = palette.white },
  ['@variable.builtin'] = { fg = palette.orange },
  ['@variable.parameter'] = { fg = palette.orange },
}
